### ISSUE TITLE
sorry，i do not know what this issues call

### ISSUE THREAD

**Issue by huhu415** [Banaanhangwagen/WINHELLO2hashcat#3]
PS C:\Users\47520\Downloads\WINHELLO2hashcat-main> python WINHELLO2hashcat.py --cryptokeys C:\Windows\ServiceProfiles\LocalService\AppData\Roaming\Microsoft\Crypto\Keys --masterkey C:\Windows\System32\Microsoft\Protect\S-1-5-18\User --system C:\Windows\System32\config\SYSTEM --security C:\Windows\System32\config\SECURITY --ngc C:\Windows\ServiceProfiles\LocalService\AppData\Local\Microsoft\Ngc --software C:\Windows\System32\config\SOFTWARE
Traceback (most recent call last):
  File "C:\Users\47520\Downloads\WINHELLO2hashcat-main\WINHELLO2hashcat.py", line 250, in <module>
    protector_by_sid = parse_ngc_dir(args.ngc, args.software)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\47520\Downloads\WINHELLO2hashcat-main\WINHELLO2hashcat.py", line 79, in parse_ngc_dir
    protector_by_sids[sid] = parse_protector_subdir(sid, first_protectors_dirpath)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\47520\Downloads\WINHELLO2hashcat-main\WINHELLO2hashcat.py", line 107, in parse_protector_subdir
    raise FileNotFoundError(f'Cannot find the GUID file (2.dat) in the subdir "{subdir_path}".')
FileNotFoundError: Cannot find the GUID file (2.dat) in the subdir "C:\Windows\ServiceProfiles\LocalService\AppData\Local\Microsoft\Ngc\{66F4FF02-CE52-4975-A041-76716E874764}\Protectors\1".
can you help me?

**Comment by Banaanhangwagen** [comment]
The error is pretty clear: "FileNotFoundError: Cannot find the GUID file (2.dat)"

If there is no PIN_GUID in the `NGC\GUID\Protectors\1`-folder (2.dat), and the 1.dat (same folder) tells you "MS Platform Crypto Provider" is used, this means that the values are stored in the TPM-chip.
