### ISSUE TITLE
Don't have perms to open NGC

### ISSUE THREAD

**Issue by zipcord24** [Banaanhangwagen/WINHELLO2hashcat#6]
C:\Users\me\AppData\Local\Programs\Python\Python311>python C:\users\me\desktop\WINHELLO2hashcat.py --cryptokeys c:\Windows\ServiceProfiles\LocalService\AppData\Roaming\Microsoft\Crypto\Keys --masterkey c:\Windows\System32\Microsoft\Protect\S-1-5-18\User --system C:\system.dump --security C:\security.dump --ngc c:\Windows\ServiceProfiles\LocalService\AppData\Local\Microsoft\Ngc
Traceback (most recent call last):
  File "C:\users\me\desktop\WINHELLO2hashcat.py", line 250, in <module>
    protector_by_sid = parse_ngc_dir(args.ngc, args.software)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\users\me\desktop\WINHELLO2hashcat.py", line 61, in parse_ngc_dir
    for d in os.listdir(ngcdir_path):
             ^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [WinError 5] Access is denied: 'c:\\Windows\\ServiceProfiles\\LocalService\\AppData\\Local\\Microsoft\\Ngc'

C:\Users\me\AppData\Local\Programs\Python\Python311>whoami
nt authority\system

**Comment by Banaanhangwagen** [comment]
Please follow the steps as explained in the readme, and you should be fine.
